import {createHash} from 'node:crypto'
import {mkdir,readFile,writeFile} from 'node:fs/promises'

type Kind='trace'|'furniture'
type CatalogItem={id:string;cell:[number,number];roles:string[];kind:Kind;status?:'accepted'|'rejected';reason?:string}
type Rect={x:number;y:number;w:number;h:number}
type Slot={id:string;zone:string;role:string;rect:Rect;obstacle?:Rect}
type Plan={version:number;scene:string;generatorJob:string;generatedAtlas:string;fallbackAtlas:string;catalog:CatalogItem[];fallbackCatalog:CatalogItem[];slots:Slot[]}
type Manifest={jobs:Record<string,{status:string;sha256?:string;requestId?:string;output?:string}>}
type Processed=Record<string,{sourceSha256:string;sourceRequestId:string;output:string;sha256:string}>

const plan=JSON.parse(await readFile('assets/large-scene-generation-plan.json','utf8')) as Plan
const manifest=JSON.parse(await readFile('assets/platform-media.json','utf8')) as Manifest
const processed=JSON.parse(await readFile('assets/platform-processed.json','utf8')) as Processed
const media=manifest.jobs[plan.generatorJob],prepared=processed[plan.generatorJob]
const forcedFallback=process.env.ALTERU_DETAIL_PACK_FORCE_FALLBACK==='1'
const generatedReady=!forcedFallback&&media?.status==='succeeded'&&Boolean(media.sha256)&&media.sha256===prepared?.sourceSha256&&media.requestId===prepared?.sourceRequestId
const accepted=plan.catalog.filter(item=>item.status==='accepted')
const counters=new Map<string,number>()
const details=plan.slots.map(slot=>{
 const generated=accepted.filter(item=>item.roles.includes(slot.role))
 const fallbacks=plan.fallbackCatalog.filter(item=>item.roles.includes(slot.role))
 const pool=generatedReady&&generated.length?generated:fallbacks
 if(!pool.length)throw new Error(`NO_ASSET_FOR_SLOT:${slot.id}:${slot.role}`)
 const offset=counters.get(slot.role)??0,item=pool[offset%pool.length]
 counters.set(slot.role,offset+1)
 const usingGenerated=generatedReady&&generated.includes(item)
 return {id:slot.id,zone:slot.zone,role:slot.role,rect:slot.rect,...(item.kind==='furniture'&&slot.obstacle?{obstacle:slot.obstacle}:{}),kind:item.kind,assetId:item.id,cell:item.cell,atlas:usingGenerated?plan.generatedAtlas:plan.fallbackAtlas,source:usingGenerated?'generated':'fallback'}
})
const report={version:plan.version,scene:plan.scene,generatorJob:plan.generatorJob,generatedReady,forcedFallback,sourceSha256:media?.sha256??null,processedSha256:prepared?.sha256??null,acceptedAssets:accepted.map(item=>item.id),rejectedAssets:plan.catalog.filter(item=>item.status==='rejected').map(item=>({id:item.id,reason:item.reason})),fallbackAssets:plan.fallbackCatalog.map(item=>item.id),slotCount:details.length,generatedSlots:details.filter(item=>item.source==='generated').length,fallbackSlots:details.filter(item=>item.source==='fallback').length,planSha256:createHash('sha256').update(JSON.stringify(plan)).digest('hex')}
const source=`/* Generated by scripts/build-large-scene-pack.ts. Do not edit by hand. */\nexport const largeDetailPackMeta=${JSON.stringify(report,null,2)} as const\nexport const largeGeneratedDetails=${JSON.stringify(details,null,2)} as const\n`
await mkdir('src/generated',{recursive:true})
await writeFile('src/generated/large-scene-detail-pack.ts',source)
await writeFile('assets/large-scene-detail-pack-report.json',JSON.stringify(report,null,2)+'\n')
console.log(JSON.stringify(report))
