import {createHash,randomUUID} from 'node:crypto'
import {existsSync,mkdirSync,readFileSync,writeFileSync} from 'node:fs'
import {dirname} from 'node:path'
import {submitImageMedia,getMediaTask,waitForMediaTask,MediaServiceError} from './media-service'

const sessionId='b198e25d-5781-48c3-930a-143ed23a92b4'
const apiBase='https://game.aiwaves.tech/alteru-media/api'
const ledgerPath='assets/benchmark/hero-v7/platform-ledger.json'
const platform=JSON.parse(readFileSync('assets/platform-media.json','utf8')) as {jobs:Record<string,{url?:string}>}
const reference=(id:string)=>{const url=platform.jobs[id]?.url;if(!url)throw new Error(`Missing public reference URL for ${id}`);return url}

type Job={id:string;referenceJob?:string;poseGuideJob?:string;mode?:'text'|'edit';size:{width:number;height:number};output:string;prompt:string}
const oppositeSidePrompt='Edit this reference into the OPPOSITE left-walking contact phase for the exact same character. Preserve its head, hair, face, coat, teal collar, brass tag, camera, pixel density, scale and strict SCREEN-LEFT profile. The shoe currently farthest to SCREEN LEFT must move back beneath the coat as the support leg; the other leg must cross and plant forward toward SCREEN LEFT, clearly changing which leg owns the forward shoe. Keep one stable ground baseline and natural opposite arm swing. Do not duplicate the source phase, reflect only the lower body, split or add legs, rotate the torso, show a frontal face, add crowns, bags, shadows, floor, words or grid. Exactly one full body centered on uniform pure #FF00FF.'
const oppositeDownPrompt='Edit this reference into the OPPOSITE straight-down walking contact phase for the exact same character. Preserve the head, crown-dominant steep overhead camera, narrow downcast face, indigo coat, teal collar, brass tag, body scale and center. Move the currently forward leg back beneath the coat and plant the other leg toward the bottom of canvas; support legs must truly exchange with a natural opposite arm swing. Do not turn sideways, duplicate the same phase, reflect only the lower body, add or split limbs, change identity, add shadow, floor, grid or text. One full body on uniform pure #FF00FF with the same sole baseline.'
const oppositeUpPrompt='Edit this reference into the OPPOSITE straight-up walking contact phase for the exact same back-facing character. Preserve back of charcoal head, teal collar, indigo coat, steep overhead camera, identity, scale and center; absolutely no face or side turn. Exchange the supporting legs so the currently advanced leg recedes and the other advances toward the top of canvas, with natural opposite arm swing and one stable sole baseline. No duplicate phase, lower-body reflection, added/split limbs, shadow, floor, grid or text. One full body on uniform pure #FF00FF.'
const sidePassPrompt='Animate this exact neutral SCREEN-LEFT character into a compact passing step, not a wide contact pose. Keep strict left profile and the exact same head, hair, face, indigo coat, teal collar, brass tag, pixel density, body scale and steep overhead B-view camera. The planted foot stays directly under the torso while the other knee bends and its heel lifts behind, so both legs overlap naturally and the silhouette is clearly different from a wide split-leg stride. Add a small opposite arm swing. One stable ground baseline; no floating support foot, extra limb, split leg, frontal rotation, lower-body reflection, shadow, floor, text, grid, bag or new object. Exactly one full body centered on uniform pure #FF00FF.'
const sideTextPassPrompt='One isolated full-body pixel RPG protagonist in a compact passing step moving SCREEN LEFT. Identity: ordinary young adult, short charcoal-black hair with long fringe, worn deep indigo knee-length coat, muted teal collar, dark charcoal trousers and brown-black shoes, tiny square brass memory tag on left chest. Strict left profile in steep B-view orthographic overhead camera; visible hair crown, only one eye or no eye, mature non-chibi proportions. Pose: the planted foot is directly under the torso; the other knee bends behind with heel lifted close to the calf, so the legs overlap and are NOT spread into a wide stride. Opposite arms swing subtly. Crisp mature pixel-painted clusters, one stable ground baseline. Exactly one character centered on perfectly uniform pure #FF00FF. No floor, shadow, text, grid, bag, extra limb, frontal turn or second pose.'
const jobs:Job[]=[
 {id:'hero-down-strip-v7',referenceJob:'hero-stand-down-v5',size:{width:1536,height:512},output:'assets/platform/hero-v7/hero-down-strip-v7.png',prompt:'Create ONE horizontal three-cell walking strip of the exact same young newly uploaded adult in the reference: short charcoal hair, worn deep indigo coat, muted teal collar, dark trousers and shoes, tiny brass memory tag. Strict B-view orthographic steep overhead pixel RPG camera. Three equal 512x512 cells, left to right: LEFT LEG support/other leg swinging, neutral feet-together stand, RIGHT LEG support/opposite leg swinging. The two walking cells must be genuinely different anatomical phases, not mirrored lower-body collage, not duplicated legs. Head, hair, coat, shoulders, tag, scale and identity remain identical; crown dominates and face is only a narrow downcast sliver. Each full body centered in its own cell with the same sole baseline near y450. Mature crisp pixel-painted clusters. Perfect uniform #FF00FF background outside figures. No grid lines, text, floor, shadow, UI, extra people, frontal portrait or diagonal turn.'},
 {id:'hero-left-strip-v7',referenceJob:'hero-stand-left-v5',size:{width:1536,height:512},output:'assets/platform/hero-v7/hero-left-strip-v7.png',prompt:'Create ONE horizontal three-cell walking strip of this exact same indigo-coat character facing SCREEN LEFT in strict B-view overhead pixel RPG projection. Three equal 512x512 cells: first a left-facing step with the nearer leg supporting and the far leg passing, center a neutral left-facing stand, third the opposite step with support legs truly exchanged. Both step cells must remain strict left profile with nose pointing left and visible hair crown; do not rotate toward viewer or show the back. Preserve identical hair, face, teal collar, coat length, buttons, brass tag, shoulder width, total scale and shoe baseline across all cells. Real alternating anatomy, no reflected lower-body collage, duplicated pose, split legs or floating feet. Uniform pure #FF00FF outside figures, no grid, labels, floor, shadow, bag or extra object.'},
 {id:'hero-up-strip-v7',referenceJob:'hero-stand-up-v5',size:{width:1536,height:512},output:'assets/platform/hero-v7/hero-up-strip-v7.png',prompt:'Create ONE horizontal three-cell walking strip of this exact same indigo-coat character facing STRAIGHT UP, away from viewer, in strict B-view overhead pixel RPG projection. Three equal 512x512 cells: left support phase, neutral feet-together stand, opposite right support phase. Back of charcoal hair, teal collar and coat remain visible in every cell; absolutely no face, eye or side turn. Support legs and opposite arm swing must genuinely exchange between first and third cells, with stable torso, identity, scale and common sole baseline. No mirrored lower-body collage or duplicate phase. Uniform #FF00FF background, no grid, text, floor, shadow, bag or extra person.'},
 {id:'hero-side-opposite-v8a',referenceJob:'hero-step-left-l-v5',poseGuideJob:'hero-walk-v4',size:{width:512,height:512},output:'assets/platform/hero-v7/hero-side-opposite-v8a.png',prompt:oppositeSidePrompt},
 {id:'hero-side-opposite-v8b',referenceJob:'hero-step-left-l-v5',poseGuideJob:'hero-walk-v4',size:{width:512,height:512},output:'assets/platform/hero-v7/hero-side-opposite-v8b.png',prompt:oppositeSidePrompt},
 {id:'hero-side-opposite-v8c',referenceJob:'hero-step-left-l-v5',poseGuideJob:'hero-walk-v4',size:{width:512,height:512},output:'assets/platform/hero-v7/hero-side-opposite-v8c.png',prompt:oppositeSidePrompt},
 {id:'hero-side-pass-v9a',referenceJob:'hero-stand-left-v5',size:{width:512,height:512},output:'assets/platform/hero-v7/hero-side-pass-v9a.png',prompt:sidePassPrompt},
 {id:'hero-side-pass-v9b',referenceJob:'hero-stand-left-v5',size:{width:512,height:512},output:'assets/platform/hero-v7/hero-side-pass-v9b.png',prompt:sidePassPrompt},
 {id:'hero-side-pass-v9c',referenceJob:'hero-stand-left-v5',size:{width:512,height:512},output:'assets/platform/hero-v7/hero-side-pass-v9c.png',prompt:sidePassPrompt},
 {id:'hero-side-text-pass-v10a',mode:'text',size:{width:512,height:512},output:'assets/platform/hero-v7/hero-side-text-pass-v10a.png',prompt:sideTextPassPrompt},
 {id:'hero-side-text-pass-v10b',mode:'text',size:{width:512,height:512},output:'assets/platform/hero-v7/hero-side-text-pass-v10b.png',prompt:sideTextPassPrompt},
 {id:'hero-side-text-pass-v10c',mode:'text',size:{width:512,height:512},output:'assets/platform/hero-v7/hero-side-text-pass-v10c.png',prompt:sideTextPassPrompt},
 {id:'hero-side-text-pass-v10d',mode:'text',size:{width:512,height:512},output:'assets/platform/hero-v7/hero-side-text-pass-v10d.png',prompt:sideTextPassPrompt},
 {id:'hero-down-opposite-v8a',referenceJob:'hero-step-down-l-v5',poseGuideJob:'hero-walk-v4',size:{width:512,height:512},output:'assets/platform/hero-v7/hero-down-opposite-v8a.png',prompt:oppositeDownPrompt},
 {id:'hero-down-opposite-v8b',referenceJob:'hero-step-down-l-v5',poseGuideJob:'hero-walk-v4',size:{width:512,height:512},output:'assets/platform/hero-v7/hero-down-opposite-v8b.png',prompt:oppositeDownPrompt},
 {id:'hero-up-opposite-v8a',referenceJob:'hero-step-up-l-v5',poseGuideJob:'hero-walk-v4',size:{width:512,height:512},output:'assets/platform/hero-v7/hero-up-opposite-v8a.png',prompt:oppositeUpPrompt},
 {id:'hero-up-opposite-v8b',referenceJob:'hero-step-up-l-v5',poseGuideJob:'hero-walk-v4',size:{width:512,height:512},output:'assets/platform/hero-v7/hero-up-opposite-v8b.png',prompt:oppositeUpPrompt},
 {id:'home-side-wall-v7',referenceJob:'home-wall-v5',size:{width:256,height:1536},output:'assets/platform/walls/home-side-wall-v7.png',prompt:'Using the reference only for exact material palette, pixel-painted density, light direction and restrained wear, create a tall uninterrupted SIDE WALL texture module for the same B-view orthographic room. It is a straight vertical architectural wall strip viewed from steep overhead: continuous muted blue-gray inner face, narrow top cap, thin dark outer edge and subtle bottom trim. No windows, frames, screens, pipes, doors, bright white panels, isolated highlights, corner wedges, furniture, floor, text or symbols. Fill the entire 256x1536 canvas edge to edge with coherent wall construction; no surrounding background and no perspective convergence. Texture must remain continuous through the central vertical band because runtime crops it narrowly.'},
 {id:'hall-side-wall-v7',referenceJob:'hall-wall-v4',size:{width:256,height:1536},output:'assets/platform/walls/hall-side-wall-v7.png',prompt:'Using the reference only for exact cool gray-green material palette, pixel-painted density and light direction, create a tall uninterrupted SIDE WALL texture module for the same B-view orthographic public hall. Straight vertical architectural wall viewed from steep overhead, continuous inner face, narrow cap, thin dark edge and restrained lower trim. No fixtures, windows, pictures, lamps, doors, bright white blocks, isolated highlights, floor, furniture, text or symbols. Fill the complete 256x1536 canvas with one coherent wall; no perspective convergence. The central vertical band must be continuous for a narrow runtime crop.'},
 {id:'service-side-wall-v7',referenceJob:'service-wall-v4',size:{width:256,height:1536},output:'assets/platform/walls/service-side-wall-v7.png',prompt:'Using the reference only for exact cool service-room blue-gray material, muted brass accents, pixel density and light direction, create a tall uninterrupted SIDE WALL texture module for the same B-view orthographic memory service room. Straight vertical wall viewed from steep overhead with continuous inner face, narrow cap, thin dark edge and subtle lower trim. No consoles, screens, plaques, windows, doors, bright white panels, isolated highlights, floor, furniture, text or symbols. Fill all 256x1536 pixels edge to edge, no background and no perspective convergence. Keep the central crop band continuous.'},
]

type Attempt={requestId:string;taskId?:string;status:'failed';error?:string;retryable?:boolean}
type LedgerEntry={requestId:string;taskId?:string;status:'pending'|'succeeded'|'failed';referenceUrl:string;prompt:string;output:string;url?:string;sha256?:string;size?:[number,number];timingMs?:number;error?:string;retryable?:boolean;previousAttempts?:Attempt[]}
type Ledger={sessionId:string;apiBase:string;startedAt:string;updatedAt:string;jobs:Record<string,LedgerEntry>}
const ledger:Ledger=existsSync(ledgerPath)?JSON.parse(readFileSync(ledgerPath,'utf8')):{sessionId,apiBase,startedAt:new Date().toISOString(),updatedAt:new Date().toISOString(),jobs:{}}
const save=()=>{ledger.updatedAt=new Date().toISOString();mkdirSync(dirname(ledgerPath),{recursive:true});writeFileSync(ledgerPath,JSON.stringify(ledger,null,2)+'\n')}

async function download(url:string,path:string){const response=await fetch(url);if(!response.ok)throw new Error(`Download failed ${response.status}`);const bytes=Buffer.from(await response.arrayBuffer());mkdirSync(dirname(path),{recursive:true});writeFileSync(path,bytes);return createHash('sha256').update(bytes).digest('hex')}

async function run(job:Job){
 const referenceUrl=job.referenceJob?reference(job.referenceJob):''
 let entry=ledger.jobs[job.id]
 if(entry?.status==='succeeded'&&entry.sha256&&existsSync(entry.output))return
 if(!entry){entry=ledger.jobs[job.id]={requestId:randomUUID(),status:'pending',referenceUrl,prompt:job.prompt,output:job.output};save()}
 if(entry.status==='failed'&&entry.retryable===false){
  entry.previousAttempts=[...(entry.previousAttempts??[]),{requestId:entry.requestId,taskId:entry.taskId,status:'failed',error:entry.error,retryable:entry.retryable}]
  entry.requestId=randomUUID();entry.status='pending';delete entry.taskId;delete entry.error;delete entry.retryable;save()
 }
 try{
  const referenceUrls=referenceUrl?[referenceUrl]:[]
  let task=entry.taskId?await getMediaTask(entry.taskId):await submitImageMedia({sessionId,requestId:entry.requestId,mode:job.mode??'edit',prompt:job.prompt,referenceUrls,size:job.size})
  entry.taskId=task.task_id;save()
  if(task.status!=='succeeded')task=await waitForMediaTask(task,{timeoutMs:20*60_000})
  if(task.media?.type!=='image')throw new Error('Task completed without image media')
  entry.taskId=task.task_id;entry.url=task.media.url;entry.size=[task.media.width,task.media.height];entry.timingMs=task.timing_ms;entry.sha256=await download(task.media.url,job.output);entry.status='succeeded';delete entry.error;delete entry.retryable;save()
 }catch(error){entry.status='failed';entry.error=error instanceof Error?error.message:String(error);entry.retryable=error instanceof MediaServiceError?error.retryable:undefined;save();throw error}
}

await Promise.allSettled(jobs.map(run)).then(results=>{const failed=results.filter(result=>result.status==='rejected');if(failed.length)throw new Error(`${failed.length} platform jobs failed`)})
console.log(ledgerPath)
