import type {DomainActionRule,Locale,StorySave} from './vendor/story/types'
export const discoveries=[
 {entity:'scent-station',action:'try-shared-scent',fact:'sharedScentTried',scene:'commons',title:['一口不存在的早餐','A breakfast that is not there'],label:['试着闻一闻早餐','Try the breakfast scent'],intro:['台上没有食物，只有一个亮着的体验按钮。','There is no food on the station, only a lit experience button.'],body:['你按下按钮，先闻到烤面包，再感觉手心有一只热杯。松开后，两种感觉一起消失。台边写着：“这是住户共享的体验，不是你自己的往事。”你仍记得刚才按过按钮，却已经回想不起那股香味。原来活着、记得发生过、保留那一刻的细节，是不同的事。','You press the button. Toast smells warm; a cup seems to rest in your palm. Both vanish when you let go. The label says: “A shared experience, not your own past.” You know you pressed it, but cannot recall the exact scent. Being alive, knowing an event happened, and keeping its detail are different things.']},
 {entity:'neighbor-keepsake',action:'read-neighbor-keepsake',fact:'keepsakeRead',scene:'neighbor-room',title:['玛拉留给来客的录音','Mara’s recording for visitors'],label:['播放留给来客的录音','Play the visitor recording'],intro:['录音旁贴着“给新来的住户”，没有私人档案。','The recording is marked “For new arrivals.” Her private files are closed.'],body:['玛拉在录音里说：“你可以听这一段。我保留了母亲叫我名字的声音，没有留下她做汤的味道。不是忘了她，是没有足够的位置装下全部细节。”旁边的空杯写着日期。她给每一天留一个普通的标记，提醒自己那天存在过。你没有打开她的私人记忆。','Mara says in the recording: “You may hear this. I kept my mother calling my name, but not the taste of her soup. I have not forgotten her. I cannot keep every detail.” A date is written on an empty cup. She leaves ordinary signs that each day existed. You do not open her private memories.']},
 {entity:'repair-scanner',action:'diagnose-voice',fact:'voiceDiagnosed',scene:'repair',title:['语音完整性检测','Voice integrity check'],label:['用回执检测缺失原因','Check the gap using your receipt'],intro:['检测台只读取回执编号，不复制你的声音。','The bench reads only a receipt number; it does not copy your voice.'],body:['检测台播放一声完整的测试音。扬声器没有损坏；你的语音也没有坏块。报告只显示：“结尾另存，读取权限被移走。”你第一次知道，不是转生把回忆弄坏了。打印条指向档案区的公开使用记录，让你带自己的回执核对。','A test tone plays cleanly. The speaker works and your voice has no damaged blocks. The report says: “Ending stored separately; read permission moved.” Transfer did not break your memory. The printout directs you to the public use register in the archive, with your own receipt.']},
 {entity:'archive-index',action:'read-archive-index',fact:'archiveIndexRead',scene:'archive',title:['档案区检索说明','Archive access guide'],label:['查看如何找自己的记录','Find your own record'],intro:['检索台把住户可查的记录和私人记忆分开。','The index separates accessible records from private memories.'],body:['输入回执编号，只能查到自己的处理日期与使用状态，不能播放别人的记忆。左侧档案架保存 23:17 的公开使用记录。桌边有人写了一句：“有记录，不等于有同意。”你可以去左边核对原件。','Your receipt number reveals your processing time and use status, never someone else’s memory. The rack on the left holds the 23:17 public use register. Someone wrote: “A record is not consent.” You can compare the original on the left.']},
] as const
export const discoveryDefaults=Object.fromEntries(discoveries.map(d=>[d.fact,false]))
export function discoveryRecords(save:StorySave){const i=save.locale==='zh'?0:1;return discoveries.map(d=>({id:d.entity,title:d.title[i],source:({commons:['公共生活区 · 共享早餐台','Commons · breakfast station'],'neighbor-room':['邻居住所 · 留言桌','Neighbor’s room · visitor table'],repair:['记忆修复铺 · 检测台','Repair shop · diagnostic bench'],archive:['档案区 · 检索台','Archive · index']} as const)[d.scene][i],known:Boolean(save.facts[d.fact]),body:d.body[i]}))}
export function explorationRules(locale:Locale):DomainActionRule[]{const i=locale==='zh'?0:1;return discoveries.map(d=>({id:d.action,intent:d.action,match:[d.action],matchMode:'exact',requirements:[{type:'fact',id:d.fact,equals:false,reason:i===0?'已记在背包的线索中。':'Saved in Backpack clues.'},...(d.action==='diagnose-voice'?[{type:'fact' as const,id:'receiptRead',equals:true,reason:i===0?'先在转生居所拿到迁入回执。':'Collect your arrival receipt at home first.'}]:[])],effects:[{type:'fact',id:d.fact,value:true}],successText:d.body[i],successChoices:[],dangerPolicy:'suppress'}))}
export function explorationComplete(f:StorySave['facts']){return discoveries.every(d=>f[d.fact])}
export function explorationNext(f:StorySave['facts'],locale:Locale){const i=locale==='zh'?0:1;return !f.sharedScentTried?['公共生活区 · 试用共享早餐台，感受数字生活。','Commons · try the breakfast station to experience digital life.'][i]:!f.neighborMet?['公共走廊 · 跟邻居交谈，认识一个在这里生活的人。','Shared Hall · meet the neighbor who lives here.'][i]:!f.keepsakeRead?['邻居住所 · 听来客录音，看看她选择留下了什么。','Neighbor’s Room · hear her visitor recording about what she kept.'][i]:!f.voiceDiagnosed?['记忆修复铺 · 用回执检测语音，查清是否是设备坏了。','Repair Shop · check your receipt to rule out a broken player.'][i]:!f.archiveIndexRead?['档案区 · 查看检索台，找到自己的原始记录。','Archive · use the index to find your original record.'][i]:null}
export const discoveryArt:Record<string,string>={'scent-station':'./art/service-maintenance-console.png','neighbor-keepsake':'./art/rebuild-20260924/voice-console.png','repair-scanner':'./art/service-maintenance-console.png','archive-index':'./art/service-memory-archive.png'}
export function chapterLabel(f:StorySave['facts'],locale:Locale){const i=locale==='zh'?0:1;return (f.neighborDebriefed?['回访','REVISIT']:f.voiceRevisited?['声音外泄','EXPOSURE']:f.kept||f.lent?['选择的代价','THE COST']:!f.receiptRead?['醒来','AWAKENING']:!f.voiceDiagnosed?['在这里生活','LIVING HERE']:['寻找结尾','THE MISSING END'])[i]}
