import type {StoryCartridge,StorySave,Locale,DomainActionRule,DomainRequirement,DomainEffect} from './vendor/story/types'
import {createInitialSave} from './vendor/story/engine/reducer'
import {resolveDomainAction,applyDomainResolution} from './vendor/story/engine/domainRules'

export type {StorySave,Locale}
export const t=(locale:Locale,zh:string,en:string)=>locale==='zh'?zh:en
export function openingNarration(locale:Locale){return [
 t(locale,'昨夜，你完成了意识上传。今天，是你作为数字生命醒来的第一天。','Last night, your consciousness upload completed. Today is your first day as a digital life.'),
 t(locale,'系统只给新转生者一个长期记忆位，其余经历会先进入临时缓存，之后可能被清空或借出。','The system gives new arrivals one long-term memory slot. Everything else enters temporary holding and may later be cleared or lent.'),
 t(locale,'桌上的语音盒亮着“你留下的第一段”。那段声音属于你，结尾却不见了。','The voice box on the table reads “Your first saved moment.” The voice is yours, but its ending is missing.'),
]}
const requirement=(id:string,equals:boolean,locale:Locale,zh:string,en:string):DomainRequirement=>({type:'fact',id,equals,reason:t(locale,zh,en)})
const set=(id:string):DomainEffect=>({type:'fact',id,value:true})
const rule=(id:string,requirements:DomainRequirement[],effects:DomainEffect[],text:string):DomainActionRule=>({id,intent:id,match:[id],matchMode:'exact',requirements,effects,successText:text,successChoices:[],dangerPolicy:'suppress'})

export function cartridge(locale:Locale):StoryCartridge{
 const tx=(zh:string,en:string)=>t(locale,zh,en)
 const yes=(id:string,zh:string,en:string)=>requirement(id,true,locale,zh,en)
 const no=(id:string,zh:string,en:string)=>requirement(id,false,locale,zh,en)
 return {schemaVersion:1,id:'memory-margin',locale,coverImage:'./art/home.png',
  copy:{title:tx('记忆余量','Memory Margin'),subtitle:tx('转生后的第一天','First day after transfer'),promise:tx('找回一段属于自己的声音。','Find the missing end of your own memory.'),enter:tx('醒来','Wake'),continue:tx('继续','Continue'),customAction:tx('询问','Ask'),itemImagingTitle:'',itemImagingBody:''},
  theme:{outer:'#0b1822',surface:'#263b43',paper:'#e8ebe3',ink:'#e8ebe3',muted:'#a9bdc1',accent:'#69c4c5',danger:'#ed8f85',gold:'#e2ad68',material:'apartment'},
  audioTheme:{material:'apartment',bpm:70,rootHz:110,scale:[0,3,7],levels:{music:0,ambient:0,sfx:0,master:0},tension:[]},
  statDefinitions:[],drawerLabels:{party:tx('已见的人','People met'),map:tx('地点','Places'),inventory:tx('随身物','Items'),log:tx('档案','Records')},
  opening:{location:tx('转生居所','Arrival Room'),time:'06:42',objective:tx('听听桌上的语音盒。','Play the voice box on the table.'),imagePrompt:'',blocks:openingNarration(locale).map((text,index)=>({id:`arrival-${index+1}`,kind:'narration' as const,text})),choices:[]},
  initialFacts:{voiceHeard:false,receiptRead:false,breakfastRead:false,neighborMet:false,caretakerMet:false,sealRead:false,hallNoticeRead:false,clerkMet:false,ledgerRead:false,termsRead:false,compared:false,kept:false,lent:false,decisionSeen:false,voiceRevisited:false,morningHandled:false,morningStored:false,neighborPreview:false,previewLogRead:false,clerkPreviewAsked:false,caretakerPreviewAsked:false,previewStopped:false,previewTraced:false,neighborDebriefed:false},
  characters:[],initialPartyMemberIds:[],initialInventory:[],initialMap:[{id:'home',label:tx('转生居所','Arrival Room'),current:true,visited:true},{id:'hall',label:tx('公共走廊','Shared Hall'),connectedTo:'home',current:false,visited:false},{id:'service',label:tx('记忆服务点','Memory Service'),connectedTo:'hall',current:false,visited:false}],demoTurns:[],domainRules:{rules:[
   rule('listen-voice',[no('voiceHeard','你已听过这段声音。','You have heard this voice.')],[set('voiceHeard')],tx('语音里，你自己说：“等我转生，我们去吃那家……”声音在店名之前断了。进度条留下整齐的一小段空白。桌上还有一张迁入回执。','You hear your own voice: “After the transfer, let’s eat at that…” It stops before the place name. A neat blank remains in the progress bar. There is an arrival receipt on the desk.')),
   rule('read-receipt',[yes('voiceHeard','先听听语音盒。','Play the voice box first.'),no('receiptRead','回执已经存入档案。','The receipt is already in your records.')],[set('receiptRead'),{type:'inventory',action:'add',itemId:'arrival-receipt',count:1,item:{id:'arrival-receipt',label:tx('迁入回执','Arrival receipt'),count:1,detail:tx('转生完成。私人记忆 01：暂存。授权栏空白。','Transfer complete. Personal memory 01: temporary hold. Authorization field blank.')}}],tx('回执上写着“转生完成”。私人记忆 01 被标为“暂存”，授权栏却是空白。下面的小字叫你去公共走廊尽头核对。','The receipt says “Transfer complete.” Personal memory 01 is marked “temporary hold,” but its authorization field is blank. Fine print sends you to the end of the shared hall.')),
   rule('read-breakfast',[no('breakfastRead','便条已经读过。','You have read the note.')],[set('breakfastRead')],tx('早餐便条压在杯下：“面包已送到。黄油味是楼里共享的，闻不见就告诉等电梯的邻居。”你端起杯子，指腹先碰到温热的陶瓷，气味才慢半拍出现。转生以后，连一顿早餐都像有人在后台替你补齐。','A note sits under the cup: “Bread delivered. The smell of butter is shared by the building. Tell the neighbor by the lift if it does not arrive.” The ceramic feels warm first; the smell follows a moment later. Since the transfer, even breakfast seems to be assembled for you somewhere out of sight.')),
   rule('to-hall',[],[{type:'map',nodeId:'hall'}],tx('走廊里有人等电梯。墙边的值守人把一张封签按得更牢，看见你时没有打招呼。','Someone waits by the lift. An attendant presses a seal more firmly onto the wall and does not greet you.')),
   rule('to-home',[],[{type:'map',nodeId:'home'}],tx('你回到那间尚未完全属于自己的房间。语音盒还在桌上。','You return to the room that does not quite feel yours. The voice box remains on the table.')),
   rule('talk-neighbor',[no('neighborMet','她刚才的话已经记下。','You have noted what she said.')],[set('neighborMet')],tx('等电梯的女孩抱着一袋热面包。她把胸牌转向你：“玛拉。你刚来吧？昨晚那位值守人把这里的自动借用口封了。有人骂他多管闲事。要查的话，封签上有时间。”她把面包往你手里塞了一只，没有索取什么。','The woman by the lift holds warm bread. She turns her name badge toward you: “Mara. You just arrived? That attendant sealed the automatic lending port last night. People complained. There is a time on the seal.” She gives you a roll and asks for nothing.')),
   rule('talk-caretaker',[no('caretakerMet','他不愿再重复。','He does not repeat himself.')],[set('caretakerMet')],tx('值守人皱着眉，把你伸向窗口方向的手挡开。袖章上写着“骆”。“叫我伊莱亚斯。新来的，先看字，再签。你们总以为好听的话不收费。”他没有解释，转身继续守着封口。','The attendant frowns and blocks your reaching hand. His sleeve reads “Elias.” “Call me Elias. New arrival, read before you sign. You people always think kind words cost nothing.” He returns to the sealed port.')),
   rule('read-seal',[no('sealRead','封签已经记下。','The seal is already recorded.')],[set('sealRead')],tx('封签写着：昨夜 23:16，自动借用口暂停。发起人是这名值守人。暂停理由只有一行：“授权栏空白，不能代签。”','The seal reads: 23:16 last night, automatic lending port suspended. The attendant signed it. One line gives the reason: “Blank authorization cannot be signed for someone else.”')),
   rule('read-hall-notice',[no('hallNoticeRead','告示已经看过。','You have read the notice.')],[set('hallNoticeRead')],tx('走廊告示一半是日常：夜间不要堵住送餐车、电梯坏了请走楼梯。最下面一张手写纸问：“如果父亲只剩一个记忆位，今天存我的名字，明天存他的生日，哪一个应该被叫作原件？”纸边被人摸得发软，没人签名。','Half the notice is ordinary: keep the breakfast cart path clear; use the stairs when the lift fails. A handwritten page below asks: “If my father has one memory slot, should he keep my name today or his birthday tomorrow? Which one is the original?” The paper is soft at the edges from many hands. No one signed it.')),
   rule('to-service',[],[{type:'map',nodeId:'service'}],tx('服务点开着暖灯。窗口职员抬头看你，像早就知道你会来。','Warm light fills the service counter. The clerk looks up as if expecting you.')),
   rule('service-to-hall',[],[{type:'map',nodeId:'hall'}],tx('你带着窗口里的话回到走廊。那张封签仍在墙上。','You return to the hall with the clerk’s words. The seal is still on the wall.')),
   rule('talk-clerk',[no('clerkMet','她已经说过了。','She has said her piece.')],[set('clerkMet')],tx('窗口职员的名牌写着“伊玛尼”。她轻声说：“刚转生，记忆偶尔缺一截很正常。我们可以替你保住最珍贵的部分。签一下就好，剩下的我会处理。”她把表格推来，手指恰好盖住了“使用人”一栏。','The clerk’s badge reads “Imani.” She speaks softly. “A gap is normal after transfer. We can protect what matters most. Just sign and I’ll handle the rest.” She slides a form forward, one finger resting over the “user” field.')),
   rule('read-ledger',[yes('receiptRead','先拿自己的回执核对。','Bring your own receipt first.'),no('ledgerRead','这条记录已经存入档案。','This entry is already in your records.')],[set('ledgerRead')],tx('公开记录：你的私人记忆 01 在 23:17 被列为“待借用”。使用人是一位未公开的永生账户；你尚未授权。记录最下方有一行红字：“签名后 30 天内不可撤回。”','Public register: your personal memory 01 was queued for lending at 23:17. The user is an undisclosed long-lived account; you have not authorized it. Red text at the bottom: “Cannot revoke for 30 days after signing.”')),
   rule('read-terms',[no('termsRead','说明牌已经看过。','You have read the terms.')],[set('termsRead')],tx('窗口边的说明牌写着：新转生者可以长期保留一段私人记忆；临时缓存会清空。有人把“保留”二字用指甲刮出一道白痕。牌背用很小的字写着“借出可腾出位置”。你想起走廊里那张没有署名的纸。','A sign by the counter says a new arrival may keep one private memory long term; temporary holding is cleared. Someone has scratched a white line through the word “keep.” In small type on the back: “Lending frees a slot.” You think of the unsigned note in the hall.')),
   rule('compare-records',[yes('receiptRead','需要自己的迁入回执。','You need your arrival receipt.'),yes('sealRead','先看看走廊的封签。','Check the seal in the hall.'),yes('ledgerRead','先查看公开使用记录。','Read the public use register.'),yes('clerkMet','先问问窗口职员。','Ask the clerk first.'),no('compared','你已核对过三处记录。','You have compared the three records.')],[set('compared')],tx('回执空白、23:16 的封口、23:17 的待借用记录对上了。语音结尾被单独放进待借用区。值守人阻止了自动代签，窗口的“保住”实际要你让出使用权。现在可以撤下借用、取回结尾，但它会占满当前唯一的长期保留位置；也可以借出 30 天，腾出这一格，期间无法收回结尾。','The blank receipt, the 23:16 seal and the 23:17 lending entry align. The ending was placed in a lending queue. The attendant stopped an automatic signature. You may withdraw it and recover the ending, filling your only long-term slot; or lend it for 30 days and free that slot, unable to recall the ending during that period.')),
   rule('choose-keep',[yes('compared','先核对记录，再决定。','Compare the records before deciding.'),no('kept','你已经选择保留。','You already chose to keep it.'),no('lent','你已经作出借用选择。','You already chose to lend it.')],[set('kept')],tx('你要求撤下待借用记录。职员的笑停了一瞬。她交还语音的结尾，但提醒你：这段记忆会占据你当前能长期保留的一整格。你知道今晚会听到完整句子，也知道下一段记忆该怎么办仍没有答案。','You remove the lending entry. The clerk’s smile pauses. She returns the missing end, warning that this memory will fill your current long-term slot. You will hear the full sentence tonight. The next memory is still a question.')),
   rule('choose-lend',[yes('compared','先核对记录，再决定。','Compare the records before deciding.'),no('kept','你已经选择保留。','You already chose to keep it.'),no('lent','你已经作出借用选择。','You already chose to lend it.')],[set('lent')],tx('你同意借用 30 天，腾出一个长期保留位置。职员立即露出放心的神情。语音结尾仍不能播放；现在你知道它因什么而缺失，也知道有人会在别处反复使用它。','You agree to lend it for 30 days and free a long-term slot. The clerk looks relieved. The ending still will not play. You now know why it is missing, and that someone else will repeatedly use it.')),
   rule('inspect-decision',[no('decisionSeen','这份处理结果已记录。','The decision is already recorded.')],[set('decisionSeen')],tx('处理台显示你的选择已经生效。你可以回居所确认语音，也可以到走廊再看看那些人。','The desk shows your decision is active. You can return home to check the voice, or revisit the people in the hall.')),
   rule('revisit-voice',[no('voiceRevisited','你已确认这段语音的状态。','You already checked the voice.')],[set('voiceRevisited')],tx('你再次按下播放。','You press play again.')),
   rule('try-save-morning',[yes('voiceRevisited','先听完原来的语音。','Check the original voice first.'),yes('kept','当前长期位置并未占满。','Your long-term slot is not full.'),no('morningHandled','你已查看早晨印象的结果。','You already checked the morning impression.')],[set('morningHandled')],tx('你按下“长期留下”。屏幕亮出你早餐时闻到的黄油味和陶瓷杯的温度，随后停在“唯一留存位已被私人记忆 01 占用”。这段早晨只在今天的临时缓存里。你拿回了昨夜的约定，也第一次看见自己会失去什么。','You press “Keep.” The screen recalls the butter smell and the warm cup, then stops: “Only long-term slot occupied by personal memory 01.” This morning stays in temporary holding for today. You recovered last night’s promise and can now see what that costs.')),
   rule('save-morning',[yes('voiceRevisited','先听完原来的语音。','Check the original voice first.'),yes('lent','当前没有借出选择。','You have not lent the original memory.'),no('morningHandled','你已查看早晨印象的结果。','You already checked the morning impression.')],[set('morningHandled'),set('morningStored')],tx('你按下“长期留下”。今早杯子的温度、面包上的黄油味和门外送餐车的声音一起落进空出的那一格。你能留下今天，却仍听不到昨夜那句约定的结尾。那一格不再空着。','You press “Keep.” The warm cup, butter smell and breakfast cart settle into the freed slot. You can keep this morning, but still cannot hear the end of last night’s promise. The slot is no longer empty.')),
   rule('ask-neighbor-preview',[yes('voiceRevisited','先回居所确认语音。','Check the voice at home first.'),yes('neighborMet','先认识那位邻居。','Speak to the neighbor first.'),no('neighborPreview','她已经说了听见声音的经过。','She has already explained what she heard.')],[set('neighborPreview')],tx('玛拉停住手里的面包袋：“昨夜服务点的窗口外放过一句‘等我转生……’。我以为是招呼新人的样本，刚才才听出是你的声音。对不起，我不该跟着哼。”她说当时屏幕写着“预览”，没有写你的名字。她怕你不信，领你看窗口下方的播放记录。','Mara stops folding her bread bag. “The service window played ‘After the transfer…’ last night. I thought it was a welcome sample. I only just recognized your voice. I am sorry I hummed along.” The screen said “preview,” not your name. Worried you will not believe her, she points you to the playback log below the counter.')),
   rule('read-preview-log',[yes('neighborPreview','先弄清玛拉听见了什么。','Ask Mara what she heard first.'),no('previewLogRead','这段记录已经收入档案。','The log is already in your records.')],[set('previewLogRead')],tx('播放记录：23:17，私人记忆 01 的开头被外放 6 秒；用途写成“供借用人预览”。授权状态却是空白。封签停住了代签，却没停住这段外放。记录没有显示谁听过，只有一个被遮住的账户栏。','Playback log: at 23:17, the first six seconds of personal memory 01 played aloud as a “preview for borrowers.” The authorization field is blank. The seal stopped an automatic signature but not this playback. The listener field is masked.')),
   rule('confront-clerk-preview',[yes('previewLogRead','先看窗口的播放记录。','Read the playback log first.'),yes('clerkMet','先认识窗口职员。','Speak to the clerk first.'),no('clerkPreviewAsked','她的解释已经记下。','You have noted her explanation.')],[set('clerkPreviewAsked')],tx('伊玛尼仍轻声说：“预览只播开头，不算借用。有人听了，才肯拿自己的空位换你的记忆。”她承认授权栏当时是空的，却又说这是整栋楼默认开启的方便功能。说完，她把“关闭预览”的按钮移到你看得到的地方，自己不碰。','Imani keeps her voice soft. “A preview plays only the opening. It is not a loan. People need to hear something before they spend a slot on it.” She admits the authorization field was blank, then calls it a helpful building default. She moves the “stop preview” control into your view without touching it herself.')),
   rule('ask-caretaker-preview',[yes('previewLogRead','先读播放记录。','Read the playback log first.'),yes('caretakerMet','先认识值守人。','Speak to the attendant first.'),no('caretakerPreviewAsked','他已经解释封签的边界。','He has explained the seal.')],[set('caretakerPreviewAsked')],tx('伊莱亚斯盯着封签：“我能拦代签，管不了窗口放哪六秒。昨夜我提过一次，他们说预览还不是使用。”他从口袋里拿出被退回的投诉回条，日期也是 23:17。“别因为我挡住一道门，就以为别处没门。”','Elias looks at the seal. “I can block a signature. I cannot decide which six seconds they play at the counter. I complained last night. They said a preview was not use.” He shows a rejected complaint stamped 23:17. “One door stopped does not mean there are no other doors.”')),
   rule('stop-preview',[yes('previewLogRead','先看清预览记录。','Read the preview log first.'),yes('clerkPreviewAsked','先问清预览是怎么回事。','Ask the clerk about previews first.'),no('previewStopped','你已经关闭预览。','You already stopped the preview.'),no('previewTraced','你已经选择追查收听账户。','You chose to trace the listener.')],[set('previewStopped')],tx('你按下“关闭预览”。屏幕上的声波熄灭，下一次试播被拒绝；此前 23:17 的匿名记录仍在，但不会再有新的六秒流出去。你拿不到收听者的账户号。','You press “Stop preview.” The waveform goes dark and the next playback is denied. The anonymous 23:17 log remains, but no new six seconds will leave this counter. You do not get the listener account number.')),
   rule('trace-preview',[yes('previewLogRead','先看清预览记录。','Read the preview log first.'),yes('clerkPreviewAsked','先问清预览是怎么回事。','Ask the clerk about previews first.'),no('previewStopped','你已经关闭预览。','You already stopped the preview.'),no('previewTraced','你已经选择追查收听账户。','You already traced the listener.')],[set('previewTraced')],tx('你允许再播一次开头。六秒里，你听见自己的声音从窗口扬声器传到走廊，陌生账户 C-09 随后亮起。你立刻关掉预览；账户号留下了，声音也确实又给别人听了一遍。','You allow one more opening playback. For six seconds your own voice carries from the counter into the hall. An unfamiliar account, C-09, lights up. You shut the preview at once. You have the account number, and someone heard your voice again.')),
   rule('debrief-neighbor',[yes('neighborPreview','先问问玛拉听见的事。','Ask Mara what she heard first.'),no('neighborDebriefed','你们已经谈过窗口的结果。','You have talked about the result.')],[set('neighborDebriefed')],tx('玛拉放下早餐袋，望向服务点。','Mara sets down the bread bag and looks toward the service counter.')),
  ]}}
}

export function initialStory(locale:Locale){const save=createInitialSave(cartridge(locale));save.entered=true;save.blocks=save.blocks.filter(b=>b.kind!=='image'&&b.kind!=='choices');return save}
export function migrateStorySave(save:StorySave){const defaults=cartridge(save.locale).initialFacts??{};const missing=Object.keys(defaults).filter(id=>save.facts[id]===undefined);if(!missing.length)return save;return {...save,facts:{...defaults,...save.facts}}}
export function objective(s:StorySave){const f=s.facts,tx=(zh:string,en:string)=>t(s.locale,zh,en)
 if(f.neighborDebriefed)return tx('这一段调查暂告一段落。你可以继续观察这个街区。','This part of the investigation is settled. You can keep exploring.')
 if(f.previewStopped||f.previewTraced)return f.neighborMet?tx('回走廊，告诉玛拉窗口发生了什么。','Return to the hall and tell Mara what happened.'):tx('回走廊，告诉那位邻居窗口发生了什么。','Return to the hall and tell the neighbor what happened.')
 if(f.previewLogRead&&!f.clerkPreviewAsked)return tx('问窗口职员：谁允许这六秒外放？','Ask the clerk who allowed those six seconds to play.')
 if(f.previewLogRead)return tx('在预览屏决定：立即关闭，或冒险追查收听账户。','At the preview screen, stop playback or risk one more to trace the listener.')
 if(f.neighborPreview)return tx('到服务点查那六秒的播放记录。','Find the six-second playback log at memory service.')
 if(f.voiceRevisited&&!f.morningHandled)return tx('语音盒还有今早的短暂印象，试试能否留下。','The voice box holds a brief impression from this morning. Try to keep it.')
 if(f.voiceRevisited)return f.neighborMet?tx('走廊里有人听过你的声音。去问玛拉。','Someone in the hall heard your voice. Ask Mara.'):tx('走廊里有人听过你的声音。去问等电梯的邻居。','Someone in the hall heard your voice. Ask the neighbor by the lift.')
 if(f.kept||f.lent)return tx('回居所，再听一次语音。','Return home and play the voice again.')
 if(f.compared)return tx('在处理台选择这段记忆的使用方式。','Choose who may use this memory at the desk.')
 if(!f.voiceHeard)return tx('听听桌上的语音盒。','Play the voice box on the table.')
 if(!f.receiptRead)return tx('查看桌上的迁入回执。','Read the arrival receipt.')
 if(!f.sealRead)return tx('去公共走廊，看看墙上的封签。','Find the seal in the shared hall.')
 if(!f.clerkMet||!f.ledgerRead)return tx('到服务点问人，并核对公开记录。','Ask at memory service and check its register.')
 return tx('在处理台并列核对回执、封签与记录。','Compare the receipt, seal and register at the desk.')
}
export function applyAction(base:StorySave,action:string){
 base=migrateStorySave(base)
 if(action==='inspect-decision'&&!base.facts.kept&&!base.facts.lent)return {save:base,accepted:false,text:t(base.locale,'还没有处理结果。','There is no decision yet.')}
 if(action==='revisit-voice'&&!base.facts.kept&&!base.facts.lent)return {save:base,accepted:false,text:t(base.locale,'先到服务点弄清缺失的结尾。','Find out about the missing ending at memory service first.')}
 if(action==='debrief-neighbor'&&!base.facts.previewStopped&&!base.facts.previewTraced)return {save:base,accepted:false,text:t(base.locale,'先处理窗口的预览。','Deal with the counter preview first.')}
 const c=cartridge(base.locale),resolution=resolveDomainAction(base,c,action);if(!resolution)throw new Error('UNKNOWN_ACTION')
 if(resolution.status==='rejected')return {save:base,accepted:false,text:resolution.reasons.join(' ')}
 const text=action==='revisit-voice'?(base.facts.kept?t(base.locale,'语音终于接上：“……旧桥口那家只开到天亮的面馆。你不用再替我记菜单。”你听见自己笑了一声。门外有人跟着开头哼了一声；你没有把这段私语给别人听过。盒子同时亮起“今早的印象：暂存”。','The voice finally continues: “…the noodle shop by the old bridge, the one open until dawn. You won’t have to remember the menu for me.” You hear yourself laugh. Outside, someone hums along with the opening. You have never played this private voice for them. The box also lights up: “This morning: temporary hold.”'):t(base.locale,'语音停在同一个缺口。屏幕下方多了一行：外部借用中，30 天内不可取回。你留住了下一个记忆的位置，却暂时听不到结尾。门外有人跟着开头哼了一声；你没有把这段私语给别人听过。盒子同时亮起“今早的印象：暂存”。','The voice stops at the same gap. A line reads: lent externally, unavailable for 30 days. You kept a slot for the next memory, but cannot hear the ending. Outside, someone hums along with the opening. You have never played this private voice for them. The box also lights up: “This morning: temporary hold.”')):action==='debrief-neighbor'?(base.facts.previewTraced?t(base.locale,'你告诉玛拉账户号 C-09。她没有说“至少查到了”，只说：“刚才窗口又响了一次。那是你的声音，应该由你决定给谁听。”她把面包袋递给你，让你自己决定要不要接。','You tell Mara about account C-09. She does not call it a win. “The counter played again just now. That was your voice. You should decide who hears it.” She offers the bread bag, leaving you free to take it or not.'):t(base.locale,'你告诉玛拉预览已经关掉。她望了眼黑下来的窗口：“昨晚我也听见了，所以我不能当作那六秒没发生。”她主动提出替你记下当时在走廊的人，但没有让你先答应什么。','You tell Mara the preview is off. She glances at the dark counter. “I heard it last night. I cannot pretend those six seconds did not happen.” She offers to note who was in the hall then, asking for nothing first.')):resolution.successText
 const save=structuredClone(base);save.scene++;save.blocks.push(...applyDomainResolution(save,c,{...resolution,successText:text}));save.objective=objective(save)
 return {save,accepted:true,text}
}
